name: "fastapi_with_postgres_image"

services:
  fastapi_todo:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    networks:
      - 'my-net'
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  postgres_db:
   image: "postgres:latest"
   restart: always
   container_name: PostgresCont
   networks:
    - 'my-net'
   volumes:
    - postgres_data:/var/lib/postgresql/data
   environment:
        - POSTGRES_USER=ahmed
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=mydatabase
   ports:
        - '5433:5432'


networks:
   my-net:

volumes:
  postgres_data:
    driver: local