FROM python:3.12
RUN pip install poetry
LABEL maintainer="AHMED"
WORKDIR /code 
COPY . /code/
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN poetry config virtualenvs.create false
RUN poetry install
CMD [ "poetry","run" ,"uvicorn","fastapi_learning.main:app" ,"--host", "0.0.0.0","--port", "8000", "--reload" ]